name: sac3
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex
  - blas
  - blosc
  - brotli
  - bzip2
  - ca-certificates
  - certifi
  - charls
  - cloudpickle
  - cudatoolkit=11.8
  - cytoolz
  - dask-core
  - dataclasses
  - decorator
  - freetype
  - giflib
  - imagecodecs
  - imageio
  - intel-openmp
  - jpeg
  - jxrlib
  - kiwisolver
  - lcms2
  - ld_impl_linux-64
  - libaec
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuv
  - libwebp
  - libzopfli
  - lz4-c
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - networkx
  - ninja
  - numpy-base
  - olefile
  - opencv
  - openjpeg
  - openssl
  - pillow
  - pip
  - pyparsing
  - python=3.7
  - python-dateutil
  - pywavelets
  - pyyaml
  - readline
  - scikit-image
  - setuptools
  - six
  - snappy
  - sqlite
  - tifffile
  - tk
  - toolz
#  - torchaudio
  - tornado
  - typing_extensions
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - absl-py
    - adversarial-robustness-toolbox
    - advertorch
    - antlr4-python3-runtime
    - apache-beam
    - armory-testbed
    - astor
    - astunparse
    - attrs
    - avro-python3
    - backcall
    - boto3
    - botocore
    - brambox
    - cachetools
    - chardet
    - cma
    - coloredlogs
    - crcmod
    - cycler
    - cython
    - dill
    - docker
    - docopt
    - fastavro
    - ffmpeg-python
    - flatbuffers
    - future
    - gast
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - googleapis-common-protos
    - grpcio
    - h5py
    - hdfs
    - httplib2
    - humanfriendly
    - idna
    - iniconfig
    - ipython
    - ipython-genutils
    - jedi
    - jmespath
    - joblib
    - jsonschema
    - keras-applications
    - keras-preprocessing
    - kornia
    - llvmlite
    - markdown
    - mypy
    - mypy-extensions
    - numba
    - numpy
    - oauth2client
    - oauthlib
    - omegaconf
    - opt-einsum
    - packaging
    - pandas
    - parso
    - patsy
    - pexpect
    - pickleshare
    - pluggy
    - promise
    - prompt-toolkit
    - protobuf
    - ptyprocess
    - py
    - pyarrow
    - pyasn1
    - pyasn1-modules
    - pycocotools
    - pydot
    - pydub
    - pygments
    - pymongo
    - pyrsistent
    - pytest
    - pytz
    - requests
    - requests-oauthlib
    - resampy
    - rsa
    - s3transfer
    - scikit-learn
    - scipy
    - statsmodels
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - tensorflow
    - tensorflow-datasets
    - tensorflow-estimator
    - tensorflow-metadata
    - termcolor
    - threadpoolctl
    - toml
    - torch
    - torchvision
    - tqdm
    - traitlets
    - typed-ast
    - urllib3
    - wcwidth
    - websocket-client
    - werkzeug
    - wrapt
    - zipp
